/**
 * Auto-generated by `pnpm supabase:types`.
 * Do not edit by hand.
 *
 * PERMISSIVE PLACEHOLDER for day 1. This shape lets day-1 code compile against
 * the schema without strict typing. After applying the initial migration, run
 * `pnpm supabase:types` to replace this file with strictly-typed table
 * definitions generated from the live schema.
 */
type GenericRow = Record<string, unknown>;

export type Database = {
  public: {
    Tables: {
      [key: string]: {
        Row: GenericRow;
        Insert: GenericRow;
        Update: GenericRow;
        Relationships: [];
      };
    };
    Views: {
      [key: string]: { Row: GenericRow; Relationships: [] };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
